language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37

install:
  - "pip install wheel tox"
  - "pip install -r requirements/development.txt"

script:
  - "tox"
  - "python setup.py bdist_wheel -d dist"

after_success:
  - "pip install dist/*.whl"

notifications:
  email: false